<?php
$zapatillas = [
    "marca" => [
        "NIKE" => [
            "nike-dunk-high" => [
                "modelo" => "Nike Dunk HIGH",
                "descripcion" => "El icono del basquetbol de los 80, creado para la cancha y convertido en un clásico urbano.",
                "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/378649-1200-1200?width=1200&height=1200&aspect=true",
                "alt_imagen" => "Zapatilla Nike Dunk High",
        ],
        "nike-dunk-low" => [
            "modelo" => "Nike Dunk Low",
            "descripcion" => "Un clásico de inspiración basquetbolera con perfil bajo y estilo urbano.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/378649-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Nike Dunk Low",
        ],
        "nike-guillermistico" => [
            "modelo" => "Guillermistico",
            "descripcion" => "Cualquiera menos el Guille...",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/378649-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Nike Guillermistico",
        ],
        "air-jordan-1-low-se" => [
            "modelo" => "Air Jordan 1 Low SE",
            "descripcion" => "Una silueta clásica de Jordan con detalles de edición especial.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1460993-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Nike Air Jordan 1 Low SE",
        ],
        "nike-pegasus-trail-5" => [
            "modelo" => "Nike Pegasus Trail 5",
            "descripcion" => "Diseñada para correr por caminos y senderos con comodidad y buen agarre.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1381241-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Nike Pegasus Trail 5",
        ],
        "nike-air-force-1-07" => [
            "modelo" => "Nike Air Force 1 '07",
            "descripcion" => "Un diseño clásico de básquet que se volvió un básico de todos los días.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/378649-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Nike Air Force 1 '07",
        ],
        "nike-air-max-90" => [
            "modelo" => "Nike Air Max 90",
            "descripcion" => "Estilo running retro con una silueta reconocible y amortiguación visible.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/378649-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Nike Air Max 90",
        ],
        "nike-air-max-270" => [
            "modelo" => "Nike Air Max 270",
            "descripcion" => "Una zapatilla urbana cómoda con una unidad Air de gran tamaño en el talón.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1381241-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Nike Air Max 270",
        ],
        "nike-blazer-mid-77" => [
            "modelo" => "Nike Blazer Mid '77",
            "descripcion" => "Inspirada en el básquet clásico, con caña media y un perfil vintage.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/378649-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Nike Blazer Mid '77",
        ],
        "nike-revolution-7" => [
            "modelo" => "Nike Revolution 7",
            "descripcion" => "Una opción liviana y versátil para caminar y salir a correr.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1381241-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Nike Revolution 7",
        ],
    ],
    "ADIDAS" => [
        "adidas-guillermistico" => [
            "modelo" => "ADIDAS Guillermistico",
            "descripcion" => "Cualquiera menos el Guille...",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1381241-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Adidas",
        ],
        "adidas-ultraboost" => [
            "modelo" => "Adidas Ultraboost",
            "descripcion" => "Zapatillas de running con amortiguación para acompañar cada paso.",
            "imagen" => "https://assets.adidas.com/images/w_600,f_auto,q_auto/d2a64cf9cd824e5d9fcc950b5eb0b2c8_9366/Zapatillas_Ultraboost_5_Azul_ID8817_HM1.jpg",
            "alt_imagen" => "Zapatilla Adidas Ultraboost",
        ],
        "adidas-stan-smith" => [
            "modelo" => "Adidas Stan Smith",
            "descripcion" => "Una silueta clásica de perfil limpio para combinar todos los días.",
            "imagen" => "https://assets.adidas.com/images/w_600,f_auto,q_auto/69721f2e7c934d909168a80e00818569_9366/Zapatillas_Stan_Smith_Blanco_M20324_01_standard.jpg",
            "alt_imagen" => "Zapatilla Adidas Stan Smith",
        ],
        "adidas-nmd-r1" => [
            "modelo" => "Adidas NMD R1",
            "descripcion" => "Diseño urbano con una mediasuela cómoda para el uso cotidiano.",
            "imagen" => "https://cdn-images.farfetch-contents.com/14/86/22/44/14862244_24360902_600.jpg",
            "alt_imagen" => "Zapatilla Adidas NMD R1",
        ],
        "adidas-aloha" => [
            "modelo" => "Adidas Aloha",
            "descripcion" => "Una zapatilla de estilo urbano con diseño cómodo y versátil.",
            "imagen" => "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/c40af072627a446aa200a84c7d07021f_9366/Aloha_Super_Beige_JQ1043_01_00_standard.jpg",
            "alt_imagen" => "Zapatilla Adidas Aloha",
        ],
        "adidas-samba-og" => [
            "modelo" => "Adidas Samba OG",
            "descripcion" => "Un clásico de inspiración deportiva que se adapta al estilo urbano.",
            "imagen" => "https://assets.adidas.com/images/w_600,f_auto,q_auto/69721f2e7c934d909168a80e00818569_9366/Zapatillas_Stan_Smith_Blanco_M20324_01_standard.jpg",
            "alt_imagen" => "Zapatilla Adidas Samba OG",
        ],
        "adidas-superstar" => [
            "modelo" => "Adidas Superstar",
            "descripcion" => "La clásica puntera de goma y un diseño que atraviesa generaciones.",
            "imagen" => "https://assets.adidas.com/images/w_600,f_auto,q_auto/69721f2e7c934d909168a80e00818569_9366/Zapatillas_Stan_Smith_Blanco_M20324_01_standard.jpg",
            "alt_imagen" => "Zapatilla Adidas Superstar",
        ],
        "adidas-gazelle" => [
            "modelo" => "Adidas Gazelle",
            "descripcion" => "Una silueta retro de perfil bajo con un estilo fácil de combinar.",
            "imagen" => "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/c40af072627a446aa200a84c7d07021f_9366/Aloha_Super_Beige_JQ1043_01_00_standard.jpg",
            "alt_imagen" => "Zapatilla Adidas Gazelle",
        ],
        "adidas-campus-00s" => [
            "modelo" => "Adidas Campus 00s",
            "descripcion" => "Inspirada en el skate y la moda urbana con una silueta robusta.",
            "imagen" => "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/c40af072627a446aa200a84c7d07021f_9366/Aloha_Super_Beige_JQ1043_01_00_standard.jpg",
            "alt_imagen" => "Zapatilla Adidas Campus 00s",
        ],
        "adidas-adizero-sl2" => [
            "modelo" => "Adidas Adizero SL 2",
            "descripcion" => "Una zapatilla liviana pensada para entrenamientos y carreras en ruta.",
            "imagen" => "https://assets.adidas.com/images/w_600,f_auto,q_auto/d2a64cf9cd824e5d9fcc950b5eb0b2c8_9366/Zapatillas_Ultraboost_5_Azul_ID8817_HM1.jpg",
            "alt_imagen" => "Zapatilla Adidas Adizero SL 2",
        ],
    ],
    "TOPPER" => [
        "topper-runner" => [
            "modelo" => "Topper Runner",
            "descripcion" => "Zapatillas livianas para corredores diarios con buena ventilación.",
            "imagen" => "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/c40af072627a446aa200a84c7d07021f_9366/Aloha_Super_Beige_JQ1043_01_00_standard.jpg",
            "alt_imagen" => "Zapatilla Topper Runner",
        ],
        "topper-classic" => [
            "modelo" => "Topper Classic",
            "descripcion" => "Diseño clásico y versátil para el uso cotidiano.",
            "imagen" => "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/c40af072627a446aa200a84c7d07021f_9366/Aloha_Super_Beige_JQ1043_01_00_standard.jpg",
            "alt_imagen" => "Zapatilla Topper Classic",
        ],
        "topper-sport" => [
            "modelo" => "Topper Sport",
            "descripcion" => "Zapatillas deportivas multifuncionales para actividades al aire libre.",
            "imagen" => "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/c40af072627a446aa200a84c7d07021f_9366/Aloha_Super_Beige_JQ1043_01_00_standard.jpg",
            "alt_imagen" => "Zapatilla Topper Sport",
        ],
        "topper-squat" => [
            "modelo" => "Topper Squat",
            "descripcion" => "Un modelo firme y cómodo para entrenar en el gimnasio.",
            "imagen" => "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/c40af072627a446aa200a84c7d07021f_9366/Aloha_Super_Beige_JQ1043_01_00_standard.jpg",
            "alt_imagen" => "Zapatilla Topper Squat",
        ],
        "topper-gondor" => [
            "modelo" => "Topper Gondor",
            "descripcion" => "Calzado versátil de perfil deportivo para acompañar la rutina diaria.",
            "imagen" => "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/c40af072627a446aa200a84c7d07021f_9366/Aloha_Super_Beige_JQ1043_01_00_standard.jpg",
            "alt_imagen" => "Zapatilla Topper Gondor",
        ],
        "topper-tie-break" => [
            "modelo" => "Topper Tie Break",
            "descripcion" => "Una silueta urbana inspirada en el calzado clásico de tenis.",
            "imagen" => "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/c40af072627a446aa200a84c7d07021f_9366/Aloha_Super_Beige_JQ1043_01_00_standard.jpg",
            "alt_imagen" => "Zapatilla Topper Tie Break",
        ],
        "topper-t350" => [
            "modelo" => "Topper T350",
            "descripcion" => "Diseño deportivo de uso diario con calce cómodo.",
            "imagen" => "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/c40af072627a446aa200a84c7d07021f_9366/Aloha_Super_Beige_JQ1043_01_00_standard.jpg",
            "alt_imagen" => "Zapatilla Topper T350",
        ],
        "topper-street" => [
            "modelo" => "Topper Street",
            "descripcion" => "Un modelo urbano pensado para combinar con ropa casual.",
            "imagen" => "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/c40af072627a446aa200a84c7d07021f_9366/Aloha_Super_Beige_JQ1043_01_00_standard.jpg",
            "alt_imagen" => "Zapatilla Topper Street",
        ],
        "topper-fast" => [
            "modelo" => "Topper Fast",
            "descripcion" => "Zapatilla liviana para moverse con comodidad durante todo el día.",
            "imagen" => "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/c40af072627a446aa200a84c7d07021f_9366/Aloha_Super_Beige_JQ1043_01_00_standard.jpg",
            "alt_imagen" => "Zapatilla Topper Fast",
        ],
        "topper-rugby" => [
            "modelo" => "Topper Rugby",
            "descripcion" => "Calzado deportivo con una construcción pensada para el movimiento.",
            "imagen" => "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/c40af072627a446aa200a84c7d07021f_9366/Aloha_Super_Beige_JQ1043_01_00_standard.jpg",
            "alt_imagen" => "Zapatilla Topper Rugby",
        ],
    ],
    "NEW BALANCE" => [
        "newbalance-574" => [
            "modelo" => "New Balance 574",
            "descripcion" => "Una silueta icónica de inspiración retro para todos los días.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/378649-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla New Balance 574",
        ],
        "newbalance-990v6" => [
            "modelo" => "New Balance 990v6",
            "descripcion" => "Un modelo de running con diseño clásico y comodidad para largas jornadas.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1460993-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla New Balance 990v6",
        ],
        "newbalance-fuelcell-rebel-v4" => [
            "modelo" => "New Balance FuelCell Rebel v4",
            "descripcion" => "Zapatilla liviana y dinámica para entrenamientos de running.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1381241-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla New Balance FuelCell Rebel v4",
        ],
        "newbalance-530" => [
            "modelo" => "New Balance 530",
            "descripcion" => "Estilo running retro con una combinación de comodidad y diseño urbano.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/378649-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla New Balance 530",
        ],
        "newbalance-327" => [
            "modelo" => "New Balance 327",
            "descripcion" => "Una silueta inspirada en el running de los años 70 con presencia moderna.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1460993-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla New Balance 327",
        ],
        "newbalance-9060" => [
            "modelo" => "New Balance 9060",
            "descripcion" => "Diseño urbano de líneas llamativas y suela de gran volumen.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1381241-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla New Balance 9060",
        ],
        "newbalance-2002r" => [
            "modelo" => "New Balance 2002R",
            "descripcion" => "Una zapatilla de inspiración running retro adaptada al estilo cotidiano.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/378649-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla New Balance 2002R",
        ],
        "newbalance-550" => [
            "modelo" => "New Balance 550",
            "descripcion" => "Silueta de básquet clásica con un perfil simple y fácil de combinar.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1460993-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla New Balance 550",
        ],
        "newbalance-fresh-foam-1080" => [
            "modelo" => "New Balance Fresh Foam X 1080",
            "descripcion" => "Zapatilla de running enfocada en la amortiguación y la comodidad.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1381241-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla New Balance Fresh Foam X 1080",
        ],
        "newbalance-860" => [
            "modelo" => "New Balance 860",
            "descripcion" => "Modelo de running diseñado para ofrecer soporte durante los entrenamientos.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/378649-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla New Balance 860",
        ],
    ],
    "JAGUAR" => [
        "jaguar-speed" => [
            "modelo" => "Jaguar Speed",
            "descripcion" => "Zapatillas ligeras para correr y entrenar con comodidad.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/378649-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Jaguar Speed",
        ],
        "jaguar-comfort" => [
            "modelo" => "Jaguar Comfort",
            "descripcion" => "Diseñadas para acompañar el uso diario con una pisada cómoda.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1460993-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Jaguar Comfort",
        ],
        "jaguar-elite" => [
            "modelo" => "Jaguar Elite",
            "descripcion" => "Una opción deportiva de líneas modernas para entrenamiento y uso diario.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1381241-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Jaguar Elite",
        ],
        "jaguar-runner" => [
            "modelo" => "Jaguar Runner",
            "descripcion" => "Diseño liviano para caminar o sumar kilómetros durante la semana.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/378649-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Jaguar Runner",
        ],
        "jaguar-street" => [
            "modelo" => "Jaguar Street",
            "descripcion" => "Estilo urbano versátil para combinar con ropa casual.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1460993-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Jaguar Street",
        ],
        "jaguar-active" => [
            "modelo" => "Jaguar Active",
            "descripcion" => "Una zapatilla cómoda para mantenerse en movimiento durante el día.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1381241-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Jaguar Active",
        ],
        "jaguar-flex" => [
            "modelo" => "Jaguar Flex",
            "descripcion" => "Modelo flexible para caminatas, salidas y actividades cotidianas.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/378649-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Jaguar Flex",
        ],
        "jaguar-classic" => [
            "modelo" => "Jaguar Classic",
            "descripcion" => "Una silueta deportiva clásica para el uso de todos los días.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1460993-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Jaguar Classic",
        ],
        "jaguar-trail" => [
            "modelo" => "Jaguar Trail",
            "descripcion" => "Calzado deportivo pensado para paseos y recorridos al aire libre.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/1381241-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Jaguar Trail",
        ],
        "jaguar-urban" => [
            "modelo" => "Jaguar Urban",
            "descripcion" => "Un diseño actual y cómodo para completar un look urbano.",
            "imagen" => "https://nikearprod.vtexassets.com/arquivos/ids/378649-1200-1200?width=1200&height=1200&aspect=true",
            "alt_imagen" => "Zapatilla Jaguar Urban",
        ],
    ],
    ],
];
